### ISSUE TITLE
影响系统性能？

### ISSUE THREAD

**Issue by ganxinming** [kevin0016/sky-eye#3]
异步是为了不影响系统业务，直接写在项目里不会影响性能吗？

**Comment by kevin0016** [comment]
对性能肯定会有影响，因为是本地调用web hook接口的，这也是为啥我把com.itkevin.common.notice.NoticeInterfacee这个接口开放出去的，如果想要尽可能小的影响就在这个接口的实现里面发MQ，让另外的服务器去执行调用web hook的步骤
